// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCompanyAttribute("Knab")]
[assembly: AssemblyCopyright("Copyright ©  2019")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyInformationalVersion = "0.0.1";
        internal const System.String AssemblyCompany = "Knab";
        internal const System.String AssemblyCopyright = "Knab";
        internal const System.Boolean ComVisible = false;
    }
}
